In [1]:
import numpy as np

In [2]:
first_array = np.arange(1,11)

In [3]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
first_array[0]

1

In [5]:
first_array[1]

2

In [6]:
first_array[-1]

10

In [7]:
#### create a tuples

In [8]:
enumerate(first_array)

In [9]:
# create a index tuples

In [10]:
list(enumerate(first_array))

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [11]:
##

In [13]:
first_array[2:6]

array([3, 4, 5, 6])

In [14]:
first_array[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
first_array[:5]

array([1, 2, 3, 4, 5])

In [16]:
first_array[6:]

array([ 7,  8,  9, 10])

In [17]:
first_array[::2]

array([1, 3, 5, 7, 9])

In [18]:
first_array[2::3]

array([3, 6, 9])

In [19]:
first_array[0] = 100 #ndarrays are mutable

In [20]:
first_array

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [21]:
first_array[-1]=101

In [22]:
first_array

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [25]:
first_array[2:5]= [50,51,52] #Broadcasting

In [26]:
first_array

array([100,   2,  50,  51,  52,   6,   7,   8,   9, 101])

In [27]:
second_array = np.arange(1,11)

In [28]:
third_array = second_array[2:8]

In [29]:
third_array

array([3, 4, 5, 6, 7, 8])

In [33]:
third_array[0] = 100  #this will not also change third_array but the index of orignal array too

In [34]:
third_array

array([100,   4,   5,   6,   7,   8])

In [35]:
second_array

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [37]:
#difference between list

In [38]:
first_list = list(range(1,11))

In [39]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [40]:
second_list = first_list[2:8]

In [41]:
second_list

[3, 4, 5, 6, 7, 8]

In [42]:
second_list[0] = 100

In [43]:
second_list

[100, 4, 5, 6, 7, 8]

In [45]:
first_list # unlike numpy array there is no change

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [46]:
#this is the problem with numpy array 

In [47]:
# .copy() method is very important in that case

In [48]:
first_array

array([100,   2,  50,  51,  52,   6,   7,   8,   9, 101])

In [51]:
f1 = first_array[2:8].copy()

In [52]:
f1[0] = 1

In [53]:
f1

array([ 1, 51, 52,  6,  7,  8])

In [54]:
first_array

array([100,   2,  50,  51,  52,   6,   7,   8,   9, 101])