In [1]:
import numpy as np

In [2]:
first_array = np.arange(1,11)

In [3]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
m1 = first_array>5

In [5]:
m1

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
m2 = (first_array >5) & (first_array<8)

In [8]:
m2

array([False, False, False, False, False,  True,  True, False, False,
       False])

In [9]:
m3 = (first_array > 5) | (first_array<8)

In [10]:
m3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
m4 = ~((first_array>5) & (first_array<8))

In [12]:
m4

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True])

In [13]:
# not is not work in vectorize so use (~) symbol

In [14]:
first_array[first_array>5]

array([ 6,  7,  8,  9, 10])

In [15]:
first_array[m1]

array([ 6,  7,  8,  9, 10])

In [16]:
first_array[m2]

array([6, 7])

In [17]:
first_array[m3]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
first_array[m4]

array([ 1,  2,  3,  4,  5,  8,  9, 10])