In [1]:
import numpy as np

In [2]:
first_array = np.arange(1,13)

In [3]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
first_array = first_array.reshape(3,4)

In [5]:
first_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
first_array[0]

array([1, 2, 3, 4])

In [12]:
first_array[:,0] #column

array([1, 5, 9])

In [13]:
second_array = first_array.copy()

In [25]:
second_array = np.arange(1,13).reshape(3,4,order='F')  #flexiable #order is changable

In [26]:
second_array

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [29]:
#row slice

In [27]:
second_array[0]

array([ 1,  4,  7, 10])

In [28]:
second_array[1]

array([ 2,  5,  8, 11])

In [30]:
second_array[-1]

array([ 3,  6,  9, 12])

In [31]:
second_array[1][1] #[row][column]

5

In [32]:
second_array[1,1]

5

In [33]:
second_array[2,-1] #third row last columns

12

In [34]:
### column

In [35]:
second_array[:,0]

array([1, 2, 3])

In [36]:
second_array[:,1]

array([4, 5, 6])

In [37]:
second_array[:,-1]

array([10, 11, 12])

In [39]:
second_array[:2,1:3]

array([[4, 7],
       [5, 8]])

In [38]:
####################################
# TRANSPOSE

In [40]:
second_array.T

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
second_array.transpose()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
second_array[:,-1] * 0

array([0, 0, 0])

In [43]:
second_array[:,-1] = second_array[:,-1]*0

In [44]:
second_array

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [45]:
####

In [46]:
third_array = np.arange(1,13).reshape(3,4)

In [47]:
third_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
third_array.sum()

78

In [49]:
third_array.sum(axis=0) #sum of each column

array([15, 18, 21, 24])

In [50]:
third_array.sum(axis=1) # axis = 1 means rows

array([10, 26, 42])

In [51]:
third_array.cumsum() #cumulative sum

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78], dtype=int32)

In [52]:
third_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]], dtype=int32)

In [53]:
third_array.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]], dtype=int32)

In [54]:
 third_array.prod()

479001600

In [55]:
third_array.prod(axis=0)

array([ 45, 120, 231, 384])

In [56]:
third_array.prod(axis=1)

array([   24,  1680, 11880])