In [1]:
import numpy as np

In [2]:
first_array = np.arange(1,13)

In [3]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
type(first_array)

numpy.ndarray

In [5]:
first_array.shape

(12,)

In [6]:
second_array = first_array.copy()

In [7]:
second_array= second_array.reshape(2,6)

In [8]:
second_array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
second_array.shape

(2, 6)

In [10]:
second_array.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
second_array.reshape(6,2).shape

(6, 2)

In [12]:
#element wise operations

In [13]:
second_array + 2

array([[ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14]])

In [14]:
second_array * 0

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [15]:
second_array - 100

array([[-99, -98, -97, -96, -95, -94],
       [-93, -92, -91, -90, -89, -88]])

In [20]:
third_array = first_array.copy()

In [21]:
len(third_array)

12

In [22]:
#so shape cant be (3,5) = 15
# or (8,2) = 16
# but it can be (2,2,3) = 2*2*3 = 12

In [25]:
third_array = third_array.reshape(2,2,3)

In [27]:
third_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
third_array.shape

(2, 2, 3)

In [30]:
type(third_array)

numpy.ndarray

In [31]:
###3

In [34]:
forth_array = np.arange(1,101).reshape(25,4)

In [35]:
forth_array

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])