In [1]:
import numpy as np

In [2]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
first_array = np.arange(1,11,2)

In [4]:
first_array

array([1, 3, 5, 7, 9])

In [5]:
##

In [6]:
first_list = [1,2,3,4]

In [7]:
first_list

[1, 2, 3, 4]

In [9]:
first_list * 2 #not an element wise operation

[1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
second_list = []
for i in first_list:
    second_list.append(i*2)
second_list

[2, 4, 6, 8]

In [12]:
### For numpy array

In [13]:
second_array = np.arange(1,5)

In [14]:
second_array

array([1, 2, 3, 4])

In [15]:
second_array * 2

array([2, 4, 6, 8])

In [16]:
second_array + 2

array([3, 4, 5, 6])

In [17]:
second_array ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [18]:
2 ** second_array

array([ 2,  4,  8, 16], dtype=int32)

In [20]:
np.sqrt(second_array) #square root

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
np.exp(second_array) #exponentiaion

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [24]:
np.log(second_array) #logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [25]:
second_array.sum()

10

In [26]:
sum(second_array)

10

In [27]:
second_array.size

4

In [28]:
len(second_array)

4

In [29]:
third_array = np.array([-2,-1,-0.5,0,1,2,3.5])

In [30]:
third_array


array([-2. , -1. , -0.5,  0. ,  1. ,  2. ,  3.5])

In [32]:
np.abs(third_array) #absolute

array([2. , 1. , 0.5, 0. , 1. , 2. , 3.5])

In [34]:
np.ceil(third_array) #round to the closet highest integer

array([-2., -1., -0.,  0.,  1.,  2.,  4.])

In [36]:
np.floor(third_array) #rount to the close lowest integer

array([-2., -1., -1.,  0.,  1.,  2.,  3.])

In [39]:
np.around([-2.23,4.23,5.55,4.22],decimals=1)

array([-2.2,  4.2,  5.6,  4.2])