In [1]:
import numpy as np

In [2]:
np.random.seed(123)
first_array = np.random.randint(1,101,11)

In [3]:
first_array

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74])

In [4]:
first_array.sort()

In [5]:
first_array

array([18, 48, 58, 67, 74, 84, 87, 93, 97, 98, 99])

In [6]:
first_array.max()

99

In [7]:
first_array.min()

18

In [8]:
max(first_array)

99

In [9]:
min(first_array)

18

In [10]:
np.mean(first_array)

74.81818181818181

In [11]:
first_array.mean()

74.81818181818181

In [13]:
np.median(first_array)

84.0

In [16]:
np.std(first_array) #squareRoot of variance. 

24.25177849829943

In [17]:
np.var(first_array)

588.1487603305785

In [18]:
np.percentile(first_array,10)

48.0

In [19]:
np.percentile(first_array,50)

84.0

In [20]:
##########################

In [21]:
np.random.seed(123)
second_arrary = np.random.randint(1,101,11)
second_arrary

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74])

In [22]:
np.random.seed(111)
third_array = np.random.randint(1,101,11)
third_array

array([85, 85, 85, 87, 20, 42, 67, 83, 41, 72, 58])

In [24]:
np.cov(second_arrary,third_array) #covariance

array([[646.96363636, -85.81818182],
       [-85.81818182, 523.09090909]])

In [25]:
np.corrcoef(first_array,second_arrary) #corelation matrix

array([[1.        , 0.03904955],
       [0.03904955, 1.        ]])